FilVideo project. Join Slingshot
filecoin-project/slingshot pull request #10
Opened 2020-09-22 02:32 UTC by jackoelv

2020-09-22 22:22 UTC, cwaring requested changes
Hi @jackoelv, thanks for your submission. Please amend the minor suggestion and restore the original template.md and we can accept this application. Thanks

2020-09-22 22:22 UTC, cwaring commented on participants/FilVideo.md
> +- Respond to add your response in each section below
```suggestion
Before submitting a PR containing your team's project information:
- Make sure you rename this file to contain your project's name
- Respond to add your response in each section below
```
please remove the default info.

2020-09-23 02:28 UTC, jackoelv commented
default info removed. thanks.

2020-09-23 11:21 UTC, cwaring commented
thanks @jackoelv you also need to restore the original `template.md` file, otherwise I'm unable to merge this PR

2020-09-23 11:38 UTC, jackoelv commented on participants/FilVideo.md
> +- Respond to add your response in each section below
add template.md to project.

2020-09-23 11:42 UTC, cwaring approved these changes

2020-09-25 07:56 UTC, jackoelv commented
@cwaring  need one more approval.

2020-09-25 14:02 UTC, cwaring commented
@dineshshenoy mind queuing this up as reviewer two?

2020-09-25 15:14 UTC, GregTheGreek approved these changes

2020-09-25 15:16 UTC, merged