add more datasets in kaggle
filecoin-project/slingshot pull request #451
Opened 2021-05-24 07:53 UTC by askender

2021-05-28 06:35 UTC, dkkapur requested changes
Thanks @askender for recommending these!
I am ok with including most of these but the NSFW and the Magic kids dataset one.

Changes requested:
1. remove these 2 datasets
2. fix size of last dataset - should be 26 GB

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| MusicNet Dataset | A curated collection of labeled classical music. | 31 GB | wav | https://www.kaggle.com/imsparsh/musicnet-dataset |
Looks good, useful open dataset with > 1k downloads.

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| CLEVR Dataset | A Diagnostic Dataset for Compositional Language and Elementary Visual Reasoning. | 19 GB | png&json | https://www.kaggle.com/timoboz/clevr-dataset |
Looks useful as well, lower downloads but might have leverage with > 5k views on Kaggle, I'm supportive of adding this as well

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| NSFW - not-safe-for-work | Classification dataset, This dataset contains content intended for individuals 18 or older. | 20 GB | jpg | https://www.kaggle.com/omeret/not-safe-for-work |
Relatively low impact, NSFW means content policy might be difficult to manage across regions etc. Let's not include this dataset for the time being

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| Magic kids dataset | A Machine Learning classification dataset. | 17 GB | jpg | https://www.kaggle.com/fedorshakhovskiy/magic-kids |
Relatively low impact - low views and downloads, suggest we skip this one for the time being as well.

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| COCO2017 | Common Objects in Context | 20 GB | jpg | https://www.kaggle.com/aishwr/coco2017 |
3k+ views, 700+ downloads. Looks OK to include!

2021-05-28 06:35 UTC, dkkapur commented on datasets.md
> +| COCO 2017 Dataset | COCO is a large-scale object detection, segmentation, and captioning dataset. | 20 GB | jpg | https://www.kaggle.com/awsaf49/coco-2017-dataset |
Similar dataset source as previous? OK to include. This one is 26 GB though, table should reflect the correct size

2021-06-03 06:58 UTC, askender commented
I recreate a new one:  https://github.com/filecoin-project/slingshot/pull/453
Changes have been made:
- remove these 2 datasets
- fix size of last dataset - should be 26 GB

2021-06-03 06:58 UTC, closed without merging